fold_path: '/kaggle/working/output/datasets/make_cv/base/train_fold.parquet'
only_first: False

candidate_info_list:
  - name: 'transition_prob_fix/base'
    max_num_candidates: 100 # 平均15,16個程度
    dir: '/kaggle/working/output/cand_unsupervised/transition_prob_fix/base'
  - name: 'transition_prob_all_fix/base' 
    max_num_candidates: 100
    dir: '/kaggle/working/output/cand_unsupervised/transition_prob_all_fix/base'
  - name: 'ranking_location/sml_cd' 
    max_num_candidates: 25
    dir: '/kaggle/working/output/cand_unsupervised/ranking_location/sml_cd'
  - name: 'ranking_location/lrg_cd' 
    max_num_candidates: 25
    dir: '/kaggle/working/output/cand_unsupervised/ranking_location/lrg_cd'
  - name: 'ranking_location_all/sml_cd' 
    max_num_candidates: 50 # こんなにない
    dir: '/kaggle/working/output/cand_unsupervised/ranking_location_all/sml_cd'
# avg_candidates: 37.74279004357495, recall_rate: 0.815107828942355

transition_prob_path: '/kaggle/working/output/cand_unsupervised/split_transition_prob_fix/base'
transition_prob_all_path: '/kaggle/working/output/cand_unsupervised/split_transition_prob_all_fix/base'
transition_prob_bidirect_all_path: '/kaggle/working/output/cand_unsupervised/split_transition_prob_bidirect_all_fix/base'
feat_transition_prob_location_dir: '/kaggle/working/output/cand_unsupervised/split_feat_transition_prob_location/base'

yad_feature_paths:
  - output/cand_unsupervised/split_ranking/base
  - output/cand_unsupervised/split_ranking_location/ken_cd
  - output/cand_unsupervised/split_ranking_location/lrg_cd
  - output/cand_unsupervised/split_ranking_location/sml_cd
  - output/cand_unsupervised/split_ranking_location/wid_cd

