FROM gcr.io/kaggle-images/python:v139

RUN apt-get update  --allow-releaseinfo-change&& \
    apt-get -y install gcc libmariadb-dev
RUN pip install mysqlclient==2.1.0

# ruff がnotebook上で設定できないのでblackとisortを入れる
RUN python3 -m pip install --upgrade pip \
    &&  pip install --no-cache-dir \
    black isort \ 
    jupyterlab_code_formatter 

RUN pip install --no-cache-dir \
    hydra-core implicit torch_geometric
    
RUN pip install torch_cluster -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
