defaults:
  - _self_
  - dir: local
  - exp: base # 実行時に書き換える
  - override hydra/job_logging: none  # hydraで自動的にログファイルが生成されるのを防ぐ

debug: False
seed: 7

hydra:
  # hydraで自動的にログファイルが生成されるのを防ぐ
  output_subdir: null
  job:
    chdir: False
  run:
    dir: .
  searchpath:
      - file://yamls