fold_path: '/kaggle/working/output/datasets/make_cv/base/train_fold.parquet'
only_first: False

candidate_info_list:
  - name: 'ranking_location/sml_cd' 
    max_num_candidates: 10
    dir: '/kaggle/working/output/cand_unsupervised/ranking_location/sml_cd'
  - name: 'ranking_location/lrg_cd' 
    max_num_candidates: 10
    dir: '/kaggle/working/output/cand_unsupervised/ranking_location/lrg_cd'
  - name: 'prob_matrix_filter/two002' 
    max_num_candidates: 60
    dir: '/kaggle/working/output/cand_unsupervised/prob_matrix_filter/two002'

#avg_candidates: 49.899372354501935, recall_rate: 0.9033869302870128
#session_count: 1, len: 9042505
#session_count: 1, avg_candidates: 48.77663361850409
#session_count: 1, recall_rate: 0.8495948992912086
#session_count: 2, len: 4287095
#session_count: 2, avg_candidates: 51.78088727307864
#session_count: 2, recall_rate: 0.9999154517894024

transition_prob_path: '/kaggle/working/output/cand_unsupervised/transition_prob_fix/base/yad2yad_feature.parquet'
transition_prob_all_path: '/kaggle/working/output/cand_unsupervised/transition_prob_all_fix/base/yad2yad_feature.parquet'
transition_prob_bidirect_all_path: '/kaggle/working/output/cand_unsupervised/transition_prob_bidirect_all_fix/base/yad2yad_feature.parquet'

prob_matrix_info_list: 
  - name: 'base'
    path: '/kaggle/working/output/cand_unsupervised/prob_matrix_filter/base/yad2yad_feature.parquet'
  - name: 'two002'
    path: '/kaggle/working/output/cand_unsupervised/prob_matrix_filter/two002/yad2yad_feature.parquet'
  - name: 'three'
    path: '/kaggle/working/output/cand_unsupervised/prob_matrix_filter/three/yad2yad_feature.parquet'

feat_transition_prob_location_dir: '/kaggle/working/output/cand_unsupervised/feat_transition_prob_location/base'

yad_feature_paths:
  - output/cand_unsupervised/ranking/base/yad_feature.parquet
  - output/cand_unsupervised/ranking_location/ken_cd/yad_feature.parquet
  - output/cand_unsupervised/ranking_location/lrg_cd/yad_feature.parquet
  - output/cand_unsupervised/ranking_location/sml_cd/yad_feature.parquet
  - output/cand_unsupervised/ranking_location/wid_cd/yad_feature.parquet 